[package]
name = "fasta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.14.0"
rayon = "1.6.0"
spin = "0.9.4"

[[bin]]
name = "fasta"
path = "fasta.rs"
