compile:
	make -C binary-trees       compile
	make -C fannkuch-redux     compile
	make -C fasta              compile
	make -C k-nucleotide       compile
	make -C mandelbrot         compile
	make -C n-body             compile
	make -C pidigits           compile
	make -C regex-redux        compile
	make -C reverse-complement compile
	make -C spectral-norm      compile
clean:
	make -C binary-trees       clean
	make -C fannkuch-redux     clean
	make -C fasta              clean
	make -C k-nucleotide       clean
	make -C mandelbrot         clean
	make -C n-body             clean
	make -C pidigits           clean
	make -C regex-redux        clean
	make -C reverse-complement clean
	make -C spectral-norm      clean
power:
	make -C binary-trees       power
#	make -C fannkuch-redux     power
	make -C fasta              power
	make -C k-nucleotide       power
	make -C mandelbrot         power
	make -C n-body             power
	make -C pidigits           power
	make -C regex-redux        power
	make -C reverse-complement power
	make -C spectral-norm      power
mem:
	make -C binary-trees       mem
#	make -C fannkuch-redux     mem
	make -C fasta              mem
	make -C k-nucleotide       mem
	make -C mandelbrot         mem
	make -C n-body             mem
	make -C pidigits           mem
	make -C regex-redux        mem
	make -C reverse-complement mem
	make -C spectral-norm      mem
run:
	make -C binary-trees       run
#	make -C fannkuch-redux     run
	make -C fasta              run
	make -C k-nucleotide       run
	make -C mandelbrot         run
	make -C n-body             run
	make -C pidigits           run
	make -C regex-redux        run
	make -C reverse-complement run
	make -C spectral-norm      run


