[package]
name = "regex-redux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.137"
pcre2-sys = "0.2.5"
rayon = "1.6.0"

[[bin]]
name = "regexredux"
path = "regexredux.rs"
