[package]
name = "foo"
version = "0.1.0"
authors = ["singh <singh@singh.com>"]

[dependencies]
generic-array = "0.14.6"
numeric-array = "0.5.2"
rayon = "1.6.0"


[[bin]]
name = "spectralnorm"
path = "spectralnorm.rs"

